"""Initial: 12 tables models

Revision ID: fdf31f1f5d2c
Revises: 
Create Date: 2026-08-11 08:14:59.670295

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fdf31f1f5d2c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('nom_complet', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'MANAGER', 'DSM', 'VIEWER', name='roleuser'), nullable=False),
    sa.Column('actif', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('ancien_statut', sa.String(length=50), nullable=True),
    sa.Column('nouveau_statut', sa.String(length=50), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dsm',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('matricule', sa.String(length=50), nullable=False),
    sa.Column('nom_complet', sa.String(length=255), nullable=False),
    sa.Column('zone_couverture', sa.String(length=255), nullable=False),
    sa.Column('telephone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('date_affectation', sa.Date(), nullable=True),
    sa.Column('statut', sa.Enum('ACTIF', 'INACTIF', name='statutdsm'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('matricule'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('partenaires',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code_partenaire', sa.String(length=50), nullable=False),
    sa.Column('nom', sa.String(length=255), nullable=False),
    sa.Column('type_partenaire', sa.Enum('DISTRIBUTEUR', 'MASTER_DEALER', 'REVENDEUR', name='typepartenaire'), nullable=False),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('ville', sa.String(length=100), nullable=True),
    sa.Column('adresse', sa.String(length=255), nullable=True),
    sa.Column('contact_principal', sa.String(length=255), nullable=True),
    sa.Column('telephone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('date_signature_contrat', sa.Date(), nullable=True),
    sa.Column('date_fin_contrat', sa.Date(), nullable=True),
    sa.Column('statut', sa.Enum('ACTIF', 'SUSPENDU', 'RESILIE', name='statutpartenaire'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code_partenaire')
    )
    op.create_table('bts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code_bts', sa.String(length=50), nullable=False),
    sa.Column('nom', sa.String(length=255), nullable=False),
    sa.Column('partenaire_id', sa.Integer(), nullable=False),
    sa.Column('operateur', sa.Enum('MTN', 'ORANGE', 'CAMTEL', 'NEXTTEL', name='operateur'), nullable=False),
    sa.Column('technologie', sa.String(length=20), nullable=True),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('ville', sa.String(length=100), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('capacite_max', sa.Float(), nullable=False),
    sa.Column('dernier_taux_saturation', sa.Float(), nullable=True),
    sa.Column('dernier_rendement', sa.Float(), nullable=True),
    sa.Column('date_dernier_releve', sa.DateTime(), nullable=True),
    sa.Column('date_mise_service', sa.Date(), nullable=True),
    sa.Column('statut', sa.Enum('ACTIF', 'MAINTENANCE', 'HORS_SERVICE', name='statutbts'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['partenaire_id'], ['partenaires.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code_bts')
    )
    op.create_table('pos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code_pos', sa.String(length=50), nullable=False),
    sa.Column('nom', sa.String(length=255), nullable=False),
    sa.Column('adresse', sa.String(length=255), nullable=True),
    sa.Column('ville', sa.String(length=100), nullable=True),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('statut', sa.Enum('ACTIF', 'SUSPENDU', 'RENOUVELLEMENT', 'CLOTURE', name='statutpos'), nullable=False),
    sa.Column('type_pos', sa.Enum('NOUVEAU', 'RECONDUIT', name='typepos'), nullable=False),
    sa.Column('partenaire_id', sa.Integer(), nullable=False),
    sa.Column('dsm_id', sa.Integer(), nullable=False),
    sa.Column('gestionnaire_id', sa.Integer(), nullable=True),
    sa.Column('date_creation', sa.Date(), nullable=False),
    sa.Column('date_expiration', sa.Date(), nullable=True),
    sa.Column('date_derniere_reconduction', sa.Date(), nullable=True),
    sa.Column('contact_principal', sa.String(length=255), nullable=True),
    sa.Column('telephone', sa.String(length=20), nullable=True),
    sa.Column('email_contact', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['dsm_id'], ['dsm.id'], ),
    sa.ForeignKeyConstraint(['gestionnaire_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['partenaire_id'], ['partenaires.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code_pos')
    )
    op.create_table('bts_releves',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bts_id', sa.Integer(), nullable=False),
    sa.Column('date_releve', sa.DateTime(), nullable=False),
    sa.Column('charge_mesuree', sa.Integer(), nullable=False),
    sa.Column('taux_saturation', sa.Float(), nullable=True),
    sa.Column('rendement', sa.Float(), nullable=True),
    sa.Column('remarque', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['bts_id'], ['bts.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('clients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code_client', sa.String(length=50), nullable=False),
    sa.Column('nom_complet', sa.String(length=255), nullable=False),
    sa.Column('telephone', sa.String(length=20), nullable=True),
    sa.Column('numero_piece_identite', sa.String(length=50), nullable=True),
    sa.Column('type_piece', sa.Enum('CNI', 'PASSEPORT', 'CARTE_SEJOUR', name='typepiece'), nullable=True),
    sa.Column('pos_id', sa.Integer(), nullable=False),
    sa.Column('date_enregistrement', sa.Date(), nullable=False),
    sa.Column('statut', sa.Enum('ACTIF', 'INACTIF', name='statutclient'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['pos_id'], ['pos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code_client')
    )
    op.create_table('primes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pos_id', sa.Integer(), nullable=False),
    sa.Column('dsm_id', sa.Integer(), nullable=True),
    sa.Column('partenaire_id', sa.Integer(), nullable=True),
    sa.Column('montant', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('date_attribution', sa.Date(), nullable=False),
    sa.Column('statut', sa.Enum('EN_ATTENTE', 'VALIDEE', 'PAYEE', 'REJETEE', name='statutprime'), nullable=False),
    sa.Column('commentaire', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['dsm_id'], ['dsm.id'], ),
    sa.ForeignKeyConstraint(['partenaire_id'], ['partenaires.id'], ),
    sa.ForeignKeyConstraint(['pos_id'], ['pos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pos_id')
    )
    op.create_table('reconductions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pos_id', sa.Integer(), nullable=False),
    sa.Column('date_reconduction', sa.Date(), nullable=False),
    sa.Column('ancienne_date_expiration', sa.Date(), nullable=False),
    sa.Column('nouvelle_date_expiration', sa.Date(), nullable=False),
    sa.Column('motif', sa.Text(), nullable=True),
    sa.Column('valide_par', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['pos_id'], ['pos.id'], ),
    sa.ForeignKeyConstraint(['valide_par'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('requetes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code_requete', sa.String(length=50), nullable=False),
    sa.Column('type_requete', sa.Enum('APPROVISIONNEMENT_SIM', 'MAINTENANCE_BTS', 'RECLAMATION_CLIENT', 'SUPPORT_POS', 'AUTRE', name='typerequete'), nullable=False),
    sa.Column('objet', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('statut', sa.Enum('OUVERTE', 'EN_COURS', 'RESOLUE', 'FERMEE', name='statutrequete'), nullable=False),
    sa.Column('priorite', sa.Enum('BASSE', 'NORMALE', 'HAUTE', 'URGENTE', name='prioriterequete'), nullable=False),
    sa.Column('partenaire_id', sa.Integer(), nullable=True),
    sa.Column('pos_id', sa.Integer(), nullable=True),
    sa.Column('bts_id', sa.Integer(), nullable=True),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('demandeur_id', sa.Integer(), nullable=False),
    sa.Column('assigne_a', sa.Integer(), nullable=True),
    sa.Column('date_creation', sa.Date(), nullable=True),
    sa.Column('date_resolution', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['assigne_a'], ['users.id'], ),
    sa.ForeignKeyConstraint(['bts_id'], ['bts.id'], ),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['demandeur_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['partenaire_id'], ['partenaires.id'], ),
    sa.ForeignKeyConstraint(['pos_id'], ['pos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code_requete')
    )
    op.create_table('sims',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('iccid', sa.String(length=22), nullable=False),
    sa.Column('numero_msisdn', sa.String(length=20), nullable=True),
    sa.Column('operateur', sa.Enum('MTN', 'ORANGE', 'CAMTEL', 'NEXTTEL', name='operateur'), nullable=False),
    sa.Column('statut', sa.Enum('EN_STOCK', 'VENDUE', 'ACTIVEE', 'DEFECTUEUSE', 'RETOURNEE', name='statutsim'), nullable=False),
    sa.Column('pos_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('date_reception_stock', sa.Date(), nullable=True),
    sa.Column('date_vente', sa.Date(), nullable=True),
    sa.Column('date_activation', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['pos_id'], ['pos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('iccid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sims')
    op.drop_table('requetes')
    op.drop_table('reconductions')
    op.drop_table('primes')
    op.drop_table('clients')
    op.drop_table('bts_releves')
    op.drop_table('pos')
    op.drop_table('bts')
    op.drop_table('partenaires')
    op.drop_table('dsm')
    op.drop_table('audit_logs')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
