"""renforcement contraintes unicite et index composites performance

Revision ID: 5e3e9bad47b9
Revises: 9842accf4594
Create Date: 2026-08-18 04:23:25.345997

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e3e9bad47b9'
down_revision: Union[str, None] = '9842accf4594'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bts', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_bts_partner_code', ['partner_id', 'code_bts'])

    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.create_index('ix_client_partner_pos', ['partner_id', 'pos_id'], unique=False)

    with op.batch_alter_table('pos', schema=None) as batch_op:
        batch_op.create_index('ix_pos_partner_expiration', ['partner_id', 'date_expiration'], unique=False)
        batch_op.create_index('ix_pos_partner_status', ['partner_id', 'status'], unique=False)
        batch_op.create_index('ix_pos_partner_type', ['partner_id', 'type_pos'], unique=False)
        batch_op.create_unique_constraint('uq_pos_partner_code', ['partner_id', 'code_pos'])

    with op.batch_alter_table('requetes', schema=None) as batch_op:
        batch_op.create_index('ix_requete_partner_statut', ['partner_id', 'statut'], unique=False)

    with op.batch_alter_table('sims', schema=None) as batch_op:
        batch_op.create_index('ix_sim_partner_pos', ['partner_id', 'pos_id'], unique=False)
        batch_op.create_index('ix_sim_partner_status', ['partner_id', 'status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sims', schema=None) as batch_op:
        batch_op.drop_index('ix_sim_partner_status')
        batch_op.drop_index('ix_sim_partner_pos')

    with op.batch_alter_table('requetes', schema=None) as batch_op:
        batch_op.drop_index('ix_requete_partner_statut')

    with op.batch_alter_table('pos', schema=None) as batch_op:
        batch_op.drop_constraint('uq_pos_partner_code', type_='unique')
        batch_op.drop_index('ix_pos_partner_type')
        batch_op.drop_index('ix_pos_partner_status')
        batch_op.drop_index('ix_pos_partner_expiration')

    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.drop_index('ix_client_partner_pos')

    with op.batch_alter_table('bts', schema=None) as batch_op:
        batch_op.drop_constraint('uq_bts_partner_code', type_='unique')

    # ### end Alembic commands ###
