"""schema initial POSTrack v4.0

Revision ID: e3b218cb1e44
Revises: 
Create Date: 2026-08-17 04:32:49.900274

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3b218cb1e44'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('partners',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_partners_code'), 'partners', ['code'], unique=True)
    op.create_index(op.f('ix_partners_id'), 'partners', ['id'], unique=False)
    op.create_table('bts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('partner_id', sa.Integer(), nullable=False),
    sa.Column('code_bts', sa.String(length=50), nullable=False),
    sa.Column('operateur', sa.String(length=100), nullable=True),
    sa.Column('technologie', sa.String(length=50), nullable=True),
    sa.Column('capacite_max', sa.Float(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('zone', sa.String(length=150), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['partner_id'], ['partners.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bts_code_bts'), 'bts', ['code_bts'], unique=False)
    op.create_index(op.f('ix_bts_id'), 'bts', ['id'], unique=False)
    op.create_index(op.f('ix_bts_partner_id'), 'bts', ['partner_id'], unique=False)
    op.create_table('dsm',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('matricule', sa.String(length=50), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('zone', sa.String(length=150), nullable=True),
    sa.Column('partner_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['partner_id'], ['partners.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dsm_id'), 'dsm', ['id'], unique=False)
    op.create_index(op.f('ix_dsm_matricule'), 'dsm', ['matricule'], unique=True)
    op.create_index(op.f('ix_dsm_partner_id'), 'dsm', ['partner_id'], unique=False)
    op.create_table('prime_periods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('partner_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('label', sa.String(length=150), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'OPEN', 'CLOSED', 'ARCHIVED', name='statutperiode'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['partner_id'], ['partners.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('partner_id', 'code', name='uq_primeperiod_partner_code')
    )
    op.create_index(op.f('ix_prime_periods_id'), 'prime_periods', ['id'], unique=False)
    op.create_index(op.f('ix_prime_periods_partner_id'), 'prime_periods', ['partner_id'], unique=False)
    op.create_table('bts_releves',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bts_id', sa.Integer(), nullable=False),
    sa.Column('date_releve', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('charge', sa.Float(), nullable=True),
    sa.Column('taux_saturation', sa.Float(), nullable=True),
    sa.Column('rendement', sa.Float(), nullable=True),
    sa.Column('commentaire', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['bts_id'], ['bts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bts_releves_bts_id'), 'bts_releves', ['bts_id'], unique=False)
    op.create_index(op.f('ix_bts_releves_id'), 'bts_releves', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=True),
    sa.Column('role', sa.Enum('ADMIN', 'PARTENAIRE', 'DSM', 'POS_HOLDER', name='role'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('dsm_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['dsm_id'], ['dsm.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('partner_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['partner_id'], ['partners.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_table('dsm_commissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('partner_id', sa.Integer(), nullable=False),
    sa.Column('dsm_id', sa.Integer(), nullable=False),
    sa.Column('prime_period_id', sa.Integer(), nullable=False),
    sa.Column('eligible_pos_count', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'CALCULATED', 'VALIDATED', 'PAID', 'REJECTED', name='statutcommission'), nullable=False),
    sa.Column('calculated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('validated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['dsm_id'], ['dsm.id'], ),
    sa.ForeignKeyConstraint(['partner_id'], ['partners.id'], ),
    sa.ForeignKeyConstraint(['prime_period_id'], ['prime_periods.id'], ),
    sa.ForeignKeyConstraint(['validated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dsm_commissions_dsm_id'), 'dsm_commissions', ['dsm_id'], unique=False)
    op.create_index(op.f('ix_dsm_commissions_id'), 'dsm_commissions', ['id'], unique=False)
    op.create_index(op.f('ix_dsm_commissions_partner_id'), 'dsm_commissions', ['partner_id'], unique=False)
    op.create_index(op.f('ix_dsm_commissions_prime_period_id'), 'dsm_commissions', ['prime_period_id'], unique=False)
    op.create_table('import_batches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('partner_id', sa.Integer(), nullable=False),
    sa.Column('imported_by', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('entity_type', sa.Enum('PARTNER', 'DSM', 'POS', 'CLIENT', 'BTS', 'BTS_RELEVE', 'SIM', 'PRIME_PERIOD', 'REQUETE', name='entitytypeimport'), nullable=False),
    sa.Column('status', sa.Enum('UPLOADED', 'VALIDATING', 'VALIDATED', 'APPLIED', 'PARTIAL', 'FAILED', name='statutimport'), nullable=False),
    sa.Column('total_rows', sa.Integer(), nullable=True),
    sa.Column('valid_rows', sa.Integer(), nullable=True),
    sa.Column('error_rows', sa.Integer(), nullable=True),
    sa.Column('error_report_path', sa.String(length=500), nullable=True),
    sa.Column('valid_rows_path', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('applied_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['imported_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['partner_id'], ['partners.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_import_batches_id'), 'import_batches', ['id'], unique=False)
    op.create_index(op.f('ix_import_batches_partner_id'), 'import_batches', ['partner_id'], unique=False)
    op.create_table('pos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code_pos', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('zone', sa.String(length=150), nullable=True),
    sa.Column('partner_id', sa.Integer(), nullable=False),
    sa.Column('dsm_id', sa.Integer(), nullable=False),
    sa.Column('holder_user_id', sa.Integer(), nullable=True),
    sa.Column('type_pos', sa.Enum('NOUVEAU', 'RECONDUIT', name='typepos'), nullable=False),
    sa.Column('status', sa.Enum('ACTIF', 'SUSPENDU', 'FERME', name='statutpos'), nullable=False),
    sa.Column('date_creation', sa.Date(), nullable=False),
    sa.Column('date_expiration', sa.Date(), nullable=False),
    sa.Column('date_derniere_reconduction', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['dsm_id'], ['dsm.id'], ),
    sa.ForeignKeyConstraint(['holder_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['partner_id'], ['partners.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pos_code_pos'), 'pos', ['code_pos'], unique=False)
    op.create_index(op.f('ix_pos_dsm_id'), 'pos', ['dsm_id'], unique=False)
    op.create_index(op.f('ix_pos_id'), 'pos', ['id'], unique=False)
    op.create_index(op.f('ix_pos_partner_id'), 'pos', ['partner_id'], unique=False)
    op.create_table('requetes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('partner_id', sa.Integer(), nullable=False),
    sa.Column('type_requete', sa.Enum('APPROVISIONNEMENT_SIM', 'MAINTENANCE_BTS', 'RECLAMATION_CLIENT', 'SUPPORT_POS', 'AUTRE', name='typerequete'), nullable=False),
    sa.Column('titre', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('priorite', sa.Enum('BASSE', 'NORMALE', 'HAUTE', 'URGENTE', name='prioriterequete'), nullable=False),
    sa.Column('statut', sa.Enum('OUVERTE', 'EN_COURS', 'EN_ATTENTE', 'RESOLUE', 'FERMEE', 'REJETEE', name='statutrequete'), nullable=False),
    sa.Column('demandeur_id', sa.Integer(), nullable=False),
    sa.Column('responsable_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['demandeur_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['partner_id'], ['partners.id'], ),
    sa.ForeignKeyConstraint(['responsable_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_requetes_id'), 'requetes', ['id'], unique=False)
    op.create_index(op.f('ix_requetes_partner_id'), 'requetes', ['partner_id'], unique=False)
    op.create_table('user_partners',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('partner_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['partner_id'], ['partners.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('clients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('partner_id', sa.Integer(), nullable=False),
    sa.Column('pos_id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('id_number', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['partner_id'], ['partners.id'], ),
    sa.ForeignKeyConstraint(['pos_id'], ['pos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clients_id'), 'clients', ['id'], unique=False)
    op.create_index(op.f('ix_clients_partner_id'), 'clients', ['partner_id'], unique=False)
    op.create_index(op.f('ix_clients_pos_id'), 'clients', ['pos_id'], unique=False)
    op.create_table('pos_performance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('partner_id', sa.Integer(), nullable=False),
    sa.Column('pos_id', sa.Integer(), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('clients_count', sa.Integer(), nullable=True),
    sa.Column('active_sims_count', sa.Integer(), nullable=True),
    sa.Column('performance_score', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('source', sa.Enum('IMPORT', 'CALCUL', 'MANUEL', name='sourceperformance'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['partner_id'], ['partners.id'], ),
    sa.ForeignKeyConstraint(['pos_id'], ['pos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pos_performance_id'), 'pos_performance', ['id'], unique=False)
    op.create_index(op.f('ix_pos_performance_partner_id'), 'pos_performance', ['partner_id'], unique=False)
    op.create_index(op.f('ix_pos_performance_pos_id'), 'pos_performance', ['pos_id'], unique=False)
    op.create_table('primes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pos_id', sa.Integer(), nullable=False),
    sa.Column('prime_period_id', sa.Integer(), nullable=False),
    sa.Column('montant', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.Enum('BROUILLON', 'EN_ATTENTE', 'VALIDEE', 'PAYEE', 'REJETEE', name='statutprime'), nullable=False),
    sa.Column('commentaire', sa.Text(), nullable=True),
    sa.Column('demandeur_id', sa.Integer(), nullable=True),
    sa.Column('validated_by', sa.Integer(), nullable=True),
    sa.Column('validated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['demandeur_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['pos_id'], ['pos.id'], ),
    sa.ForeignKeyConstraint(['prime_period_id'], ['prime_periods.id'], ),
    sa.ForeignKeyConstraint(['validated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pos_id', name='uq_prime_pos_unique')
    )
    op.create_index(op.f('ix_primes_id'), 'primes', ['id'], unique=False)
    op.create_index(op.f('ix_primes_pos_id'), 'primes', ['pos_id'], unique=False)
    op.create_index(op.f('ix_primes_prime_period_id'), 'primes', ['prime_period_id'], unique=False)
    op.create_table('reconductions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pos_id', sa.Integer(), nullable=False),
    sa.Column('old_expiration', sa.Date(), nullable=False),
    sa.Column('new_expiration', sa.Date(), nullable=False),
    sa.Column('motif', sa.Text(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['pos_id'], ['pos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reconductions_id'), 'reconductions', ['id'], unique=False)
    op.create_index(op.f('ix_reconductions_pos_id'), 'reconductions', ['pos_id'], unique=False)
    op.create_table('requete_commentaires',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('requete_id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('statut_apres', sa.Enum('OUVERTE', 'EN_COURS', 'EN_ATTENTE', 'RESOLUE', 'FERMEE', 'REJETEE', name='statutrequete'), nullable=True),
    sa.Column('commentaire', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['requete_id'], ['requetes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_requete_commentaires_id'), 'requete_commentaires', ['id'], unique=False)
    op.create_index(op.f('ix_requete_commentaires_requete_id'), 'requete_commentaires', ['requete_id'], unique=False)
    op.create_table('requete_entites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('requete_id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(length=30), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['requete_id'], ['requetes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_requete_entites_id'), 'requete_entites', ['id'], unique=False)
    op.create_index(op.f('ix_requete_entites_requete_id'), 'requete_entites', ['requete_id'], unique=False)
    op.create_table('user_pos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('pos_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['pos_id'], ['pos.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sims',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('partner_id', sa.Integer(), nullable=False),
    sa.Column('pos_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('iccid', sa.String(length=30), nullable=False),
    sa.Column('status', sa.Enum('EN_STOCK', 'ACTIVE', 'ASSIGNEE', 'RETOURNEE', 'PERDUE', name='statutsim'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['partner_id'], ['partners.id'], ),
    sa.ForeignKeyConstraint(['pos_id'], ['pos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sims_iccid'), 'sims', ['iccid'], unique=True)
    op.create_index(op.f('ix_sims_id'), 'sims', ['id'], unique=False)
    op.create_index(op.f('ix_sims_partner_id'), 'sims', ['partner_id'], unique=False)
    op.create_index(op.f('ix_sims_pos_id'), 'sims', ['pos_id'], unique=False)
    op.create_table('sim_movements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sim_id', sa.Integer(), nullable=False),
    sa.Column('partner_id', sa.Integer(), nullable=False),
    sa.Column('movement_type', sa.Enum('RECEPTION', 'VENTE', 'ACTIVATION', 'RETOUR', 'PERTE', name='typemouvementsim'), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('comment', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['partner_id'], ['partners.id'], ),
    sa.ForeignKeyConstraint(['sim_id'], ['sims.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sim_movements_id'), 'sim_movements', ['id'], unique=False)
    op.create_index(op.f('ix_sim_movements_partner_id'), 'sim_movements', ['partner_id'], unique=False)
    op.create_index(op.f('ix_sim_movements_sim_id'), 'sim_movements', ['sim_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sim_movements_sim_id'), table_name='sim_movements')
    op.drop_index(op.f('ix_sim_movements_partner_id'), table_name='sim_movements')
    op.drop_index(op.f('ix_sim_movements_id'), table_name='sim_movements')
    op.drop_table('sim_movements')
    op.drop_index(op.f('ix_sims_pos_id'), table_name='sims')
    op.drop_index(op.f('ix_sims_partner_id'), table_name='sims')
    op.drop_index(op.f('ix_sims_id'), table_name='sims')
    op.drop_index(op.f('ix_sims_iccid'), table_name='sims')
    op.drop_table('sims')
    op.drop_table('user_pos')
    op.drop_index(op.f('ix_requete_entites_requete_id'), table_name='requete_entites')
    op.drop_index(op.f('ix_requete_entites_id'), table_name='requete_entites')
    op.drop_table('requete_entites')
    op.drop_index(op.f('ix_requete_commentaires_requete_id'), table_name='requete_commentaires')
    op.drop_index(op.f('ix_requete_commentaires_id'), table_name='requete_commentaires')
    op.drop_table('requete_commentaires')
    op.drop_index(op.f('ix_reconductions_pos_id'), table_name='reconductions')
    op.drop_index(op.f('ix_reconductions_id'), table_name='reconductions')
    op.drop_table('reconductions')
    op.drop_index(op.f('ix_primes_prime_period_id'), table_name='primes')
    op.drop_index(op.f('ix_primes_pos_id'), table_name='primes')
    op.drop_index(op.f('ix_primes_id'), table_name='primes')
    op.drop_table('primes')
    op.drop_index(op.f('ix_pos_performance_pos_id'), table_name='pos_performance')
    op.drop_index(op.f('ix_pos_performance_partner_id'), table_name='pos_performance')
    op.drop_index(op.f('ix_pos_performance_id'), table_name='pos_performance')
    op.drop_table('pos_performance')
    op.drop_index(op.f('ix_clients_pos_id'), table_name='clients')
    op.drop_index(op.f('ix_clients_partner_id'), table_name='clients')
    op.drop_index(op.f('ix_clients_id'), table_name='clients')
    op.drop_table('clients')
    op.drop_table('user_partners')
    op.drop_index(op.f('ix_requetes_partner_id'), table_name='requetes')
    op.drop_index(op.f('ix_requetes_id'), table_name='requetes')
    op.drop_table('requetes')
    op.drop_index(op.f('ix_pos_partner_id'), table_name='pos')
    op.drop_index(op.f('ix_pos_id'), table_name='pos')
    op.drop_index(op.f('ix_pos_dsm_id'), table_name='pos')
    op.drop_index(op.f('ix_pos_code_pos'), table_name='pos')
    op.drop_table('pos')
    op.drop_index(op.f('ix_import_batches_partner_id'), table_name='import_batches')
    op.drop_index(op.f('ix_import_batches_id'), table_name='import_batches')
    op.drop_table('import_batches')
    op.drop_index(op.f('ix_dsm_commissions_prime_period_id'), table_name='dsm_commissions')
    op.drop_index(op.f('ix_dsm_commissions_partner_id'), table_name='dsm_commissions')
    op.drop_index(op.f('ix_dsm_commissions_id'), table_name='dsm_commissions')
    op.drop_index(op.f('ix_dsm_commissions_dsm_id'), table_name='dsm_commissions')
    op.drop_table('dsm_commissions')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_bts_releves_id'), table_name='bts_releves')
    op.drop_index(op.f('ix_bts_releves_bts_id'), table_name='bts_releves')
    op.drop_table('bts_releves')
    op.drop_index(op.f('ix_prime_periods_partner_id'), table_name='prime_periods')
    op.drop_index(op.f('ix_prime_periods_id'), table_name='prime_periods')
    op.drop_table('prime_periods')
    op.drop_index(op.f('ix_dsm_partner_id'), table_name='dsm')
    op.drop_index(op.f('ix_dsm_matricule'), table_name='dsm')
    op.drop_index(op.f('ix_dsm_id'), table_name='dsm')
    op.drop_table('dsm')
    op.drop_index(op.f('ix_bts_partner_id'), table_name='bts')
    op.drop_index(op.f('ix_bts_id'), table_name='bts')
    op.drop_index(op.f('ix_bts_code_bts'), table_name='bts')
    op.drop_table('bts')
    op.drop_index(op.f('ix_partners_id'), table_name='partners')
    op.drop_index(op.f('ix_partners_code'), table_name='partners')
    op.drop_table('partners')
    # ### end Alembic commands ###
